name: Debugae CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: debugae-front   

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Prepare artifact (zip .next + public + package.json + node_modules)
        shell: pwsh
        run: |
          if (Test-Path deploy) { Remove-Item -Recurse -Force deploy }
          New-Item -ItemType Directory deploy | Out-Null
          Copy-Item package.json, package-lock.json, next.config.js deploy -ErrorAction SilentlyContinue
          Copy-Item -Recurse .next deploy
          Copy-Item -Recurse public deploy -ErrorAction SilentlyContinue
          Copy-Item -Recurse node_modules deploy -ErrorAction SilentlyContinue
          Compress-Archive -Path deploy\* -DestinationPath app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app-artifact
          path: app.zip

  cd:
    needs: ci
    runs-on: windows-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-app-artifact
          path: ./artifact

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          package: ./artifact/app.zip

      - name: Logout
        run: az logout
